### ISSUE TITLE
[Issue] Host Down

### ISSUE THREAD

**Issue by Anon-Exploiter** [lukechilds/reverse-shell#25]
Hi, 

The host https://shell.now.sh is down and is giving a 404, was working fine around a month ago. 

**POCs:** 

![image](https://user-images.githubusercontent.com/18597330/96440536-8c2e5700-1221-11eb-98bc-bc3b99ef3254.png)

![image](https://user-images.githubusercontent.com/18597330/96440521-8769a300-1221-11eb-853b-f1289fc94a49.png)

**Comment by lukechilds** [comment]
Yeah they discontinued the old v1 API and the API is not compatible with the new v2 API. I need to host elsewhere but haven't found the time yet.

**Comment by Anon-Exploiter** [comment]
I see, how about hosting on heroku and creating a CNAME to some subdomain of any domain of yours?

**Comment by lukechilds** [comment]
I've just purchased the domain `reverse-shell.sh` for this 😅.

Yeah I'll look into Heroku. I'm very limited with free time at the moment but will try to find time for that.

I have a few other projects that are down due to Vercel or are costing me quite a bit on DigitalOcean. I really need to migrate to a dedicated server and lump everything on that.

**Comment by lukechilds** [comment]
Ok, now live on Heroku at https://reverse-shell.sh 🎉

**Comment by Anon-Exploiter** [comment]
Thanks! :grin:
